### ISSUE TITLE
Add message pulling

### ISSUE THREAD

**Issue by chuwy** [reponche/Weatherbot-2.0#10]
Right now our `main` function expectes a city argument. Let's move this functionality in a separate function `parse_cli(args)` (we'll us it later) and rework main so that it:

1. Constantly pull the telegram server for new messages (you remember how we implement a constantly running process?)
2. Parse these messages via `get_message`
3. Print output to the terminal

**Comment by reponche** [comment]
```def main():
    while True:
        data = get_updates()
        message_text = get_message(data)
        print(message_text)```
