### ISSUE TITLE
Rename bot.py to main.py

### ISSUE THREAD

**Issue by chuwy** [reponche/Weatherbot-2.0#3]
It is unclear what file is an entrypoint. By convention entrypoints used to be called `main.py` also it should be mentioned in #2

**Comment by chuwy** [comment]
Apparently, more than one file have `main` method, which is wrong.

**Comment by reponche** [comment]
Yes, I have this construction:
```
if __name__ == '__main__':
     main()
```
on two files. 
It's "yahoo_API" and "bot". I thought it's obligatory construction when you use "import" in code.
